spring.application.name=gerenciamento de usuarios.

spring.datasource.url=jdbc:postgresql://localhost:5432/usuarios
spring.datasource.username=postgres
spring.datasource.password=32321132
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret-key=U29tZVNlY3JldEtleQ==

